### PR TITLE
Initial CornerRadius support

### LINKED ISSUE #103: Make rounded corner album art
Users can adjust the size of the rounded corners of the album art.
Just like this:
Switch image into
image or 
image
I would appreciate it if this proposal could be adopted.

### PR DESCRIPTION
**Pull request by svr333**
## Summary
Adds CornerRadius to AlbumArt

## Related Issue (if applicable)
Resolves #103 

## Checklist
- [x] Project Builds & Tests pass
- [x] These changes were tested out thoroughly

### CODE REVIEW

**Comment by TechSupport26** [comment]
One thing that should be tested is Album Art that is not square but rectangular.

**Comment by svr333** [comment]
That works fine it just wont end up being a circle if you put the cornerradius to max

I have been trying to add a rounding option to album art as well but Ive been struggling to get it to work in a tooltip (mostly because it requires 2 viewmodels) but I will try to mess around with it more to get it to work

**Comment by svr333** [comment]
I couldnt get it to work (tooltips seem to have different behaviour and I just couldnt get it to work)

**Comment by TechSupport26** [comment]
I never considered the album art popup. Anyhow, I am glad that you figured it out.

**Pull request merged**
